version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    container_name: keycloak-sveltekitauth-token-rotation-demo
    ports:
      - '8888:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev -Dkeycloak.import=/tmp/test-realm.json
    volumes:
      - ./test-realm.json:/tmp/test-realm.json:ro
